include:
  - board: xiao_ble/nrf52840/zmk
    shield: nape
    artifact-name: nape-peripheral

  - board: xiao_ble/nrf52840/zmk
    shield: settings_reset
    artifact-name: nape-settings-reset

  - board: xiao_ble/nrf52840/zmk
    shield: nape
    snippet: zmk-usb-logging
    cmake-args: -DCONFIG_LOG_PROCESS_THREAD_STARTUP_DELAY_MS=8000
    artifact-name: nape-keys-debug
    
